[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/cloudflare/wirefilter?rev=6621924baf36f8ba7f603433dbe6f857ad3d5589"]
git = "https://github.com/cloudflare/wirefilter"
rev = "6621924baf36f8ba7f603433dbe6f857ad3d5589"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor/"
