[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/cloudflare/wirefilter?rev=ec8e24e26e2707a88034bfe161beeb2a4f51f8df"]
git = "https://github.com/cloudflare/wirefilter"
rev = "ec8e24e26e2707a88034bfe161beeb2a4f51f8df"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor/"
